### ISSUE TITLE
Wrong file watcher configuration

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-leo#3]
https://github.com/sublimelsp/LSP-leo/blob/6a7a81658430fcbc9d0a63fcebca9bb6dce5f285/LSP-leo.sublime-settings#L25

The property should be called "patterns" and it should be an array of patterns. Install `LSP-json` to have this validated in your editor.

**Comment by dev-sptg** [comment]
@rchl. Issue fixed in 0.17.1 release https://github.com/sublimelsp/LSP-leo/commit/35cc067ec13718acd865498e6734fb58ee5b19f8#diff-7a6e38180534e72bf944fc608393f692ca286a8eb4964deabeb85ec25cdf6ecf
